### PR TITLE
Added default travis config, default "no test" message in package

### PR DESCRIPTION
**Pull request by shanel262**

### CODE REVIEW

**Comment by mirceaalexandru** [comment]
@shanel262 can you please investigate why is still failling on travis? The target is to have traving passing.

**Comment by mirceaalexandru** [comment]
@shanel262 can you please investigate why is still crashing?

**Comment by shanel262** [comment]
@mirceaalexandru All good now 👍

**Comment by mirceaalexandru** [comment]
:+1:

**Pull request merged**
